# Generated by Django 3.1.3 on 2021-09-26 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='city',
            new_name='address_city',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='pincode',
            new_name='address_pincode',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='state',
            new_name='address_state',
        ),
    ]
